### ISSUE TITLE
Handling Irish Surnames

### ISSUE THREAD

**Issue by jdrew1303** [mediocre/whosit#8]
First off this is a great little module 👍 

There is a small issue with Irish family names. Some are perfectly fine:
![image](https://cloud.githubusercontent.com/assets/2535432/20193551/50c6e646-a786-11e6-9a04-657151c96cff.png)
![image](https://cloud.githubusercontent.com/assets/2535432/20193586/8ce22dc0-a786-11e6-91d2-852772437250.png)

But if you have a Ó as part of your family name it parses out as a middle name: 
![image](https://cloud.githubusercontent.com/assets/2535432/20195018/bef8991a-a78c-11e6-9e0b-c1435b17da80.png)

This will probably be a problem for countries that have a significant Irish lineage (UK, USA and Australia as well as Ireland 😁 )

**Comment by hugovk** [comment]
This might be related to the problem with Dutch names: https://github.com/mediocre/whosit/pull/7#event-1494997555

**Comment by mattschuette** [comment]
Version 1.2.0 now supports many surname prefixes, including `Ó` as mentioned here.
